# Form implementation generated from reading ui file '/Users/benediktursprung/Library/CloudStorage/OneDrive-Personal/scope_foundries/scopefoundry_trovatello_lab/ScopeFoundryHW/picam/picam_readout.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_layout = QtWidgets.QHBoxLayout()
        self.cb_layout.setObjectName("cb_layout")
        self.control_widget = QtWidgets.QWidget(parent=Form)
        self.control_widget.setObjectName("control_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.control_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.continuous_checkBox = QtWidgets.QCheckBox(parent=self.control_widget)
        self.continuous_checkBox.setObjectName("continuous_checkBox")
        self.gridLayout.addWidget(self.continuous_checkBox, 1, 2, 1, 1)
        self.hw_connect_checkBox = QtWidgets.QCheckBox(parent=self.control_widget)
        self.hw_connect_checkBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.hw_connect_checkBox.setObjectName("hw_connect_checkBox")
        self.gridLayout.addWidget(self.hw_connect_checkBox, 1, 0, 1, 1)
        self.background_subtract_checkBox = QtWidgets.QCheckBox(parent=self.control_widget)
        self.background_subtract_checkBox.setObjectName("background_subtract_checkBox")
        self.gridLayout.addWidget(self.background_subtract_checkBox, 1, 1, 1, 1)
        self.int_time_doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.control_widget)
        self.int_time_doubleSpinBox.setObjectName("int_time_doubleSpinBox")
        self.gridLayout.addWidget(self.int_time_doubleSpinBox, 1, 7, 1, 1)
        self.start_pushButton = QtWidgets.QPushButton(parent=self.control_widget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.gridLayout.addWidget(self.start_pushButton, 2, 7, 1, 1)
        self.update_background_pushButton = QtWidgets.QPushButton(parent=self.control_widget)
        self.update_background_pushButton.setObjectName("update_background_pushButton")
        self.gridLayout.addWidget(self.update_background_pushButton, 2, 1, 1, 1)
        self.save_h5_checkBox = QtWidgets.QCheckBox(parent=self.control_widget)
        self.save_h5_checkBox.setObjectName("save_h5_checkBox")
        self.gridLayout.addWidget(self.save_h5_checkBox, 2, 2, 1, 1)
        self.cb_layout.addWidget(self.control_widget)
        self.verticalLayout.addLayout(self.cb_layout)
        self.plot_groupBox = QtWidgets.QGroupBox(parent=Form)
        self.plot_groupBox.setObjectName("plot_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plot_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.plot_groupBox)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.x_axis_comboBox = QtWidgets.QComboBox(parent=Form)
        self.x_axis_comboBox.setObjectName("x_axis_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.x_axis_comboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.continuous_checkBox.setText(_translate("Form", "continuous"))
        self.hw_connect_checkBox.setText(_translate("Form", "HW Connect"))
        self.background_subtract_checkBox.setText(_translate("Form", "background subtract"))
        self.start_pushButton.setText(_translate("Form", "Start"))
        self.update_background_pushButton.setText(_translate("Form", "update background"))
        self.save_h5_checkBox.setText(_translate("Form", "Save h5"))
        self.plot_groupBox.setTitle(_translate("Form", "Plot"))
        self.label_3.setText(_translate("Form", "x-axis"))
